# Generated by Django 5.1.6 on 2025-07-19 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solana_wallet_address', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('current_points', models.IntegerField(default=0)),
                ('total_tokens_minted', models.IntegerField(default=0)),
                ('referral_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('referred_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
